/*
=========================================================
BIASHNET PAYMENT CONSTANTS
=========================================================

Central constants for:

- payment methods
- payment providers
- payment status
- order status
- seller fund status
- payout status
- transaction types
- completion code status
- withdrawal rules

IMPORTANT:

Keep these values stable once they are being stored
in Firestore. Changing an existing value can make
historical records difficult to interpret.
=========================================================
*/


/*
=========================================================
PAYMENT METHODS
=========================================================
*/

const PAYMENT_METHODS = {

    MPESA:
        "MPESA",

    CARD:
        "CARD",

    WALLET:
        "WALLET",

};


/*
=========================================================
PAYMENT PROVIDERS
=========================================================
*/

const PAYMENT_PROVIDERS = {

    MPESA:
        "MPESA",

    INTASEND:
        "INTASEND",

    /*
     * Internal BIASHNET wallet operations.
     */
    BIASHNET_WALLET:
        "BIASHNET_WALLET",

    /*
     * Internal escrow/holding system.
     */
    BIASHNET_ESCROW:
        "BIASHNET_ESCROW",

};


/*
=========================================================
PAYMENT STATUS
=========================================================
*/

const PAYMENT_STATUS = {

    PENDING:
        "PENDING",

    INITIATED:
        "INITIATED",

    COMPLETED:
        "COMPLETED",

    FAILED:
        "FAILED",

    CANCELLED:
        "CANCELLED",

    REFUNDED:
        "REFUNDED",

};


/*
=========================================================
ORDER STATUS
=========================================================
*/

const ORDER_STATUS = {

    PENDING_PAYMENT:
        "PENDING_PAYMENT",

    PAYMENT_INITIATED:
        "PAYMENT_INITIATED",

    PAID:
        "PAID",

    PROCESSING:
        "PROCESSING",

    READY_FOR_DELIVERY:
        "READY_FOR_DELIVERY",

    OUT_FOR_DELIVERY:
        "OUT_FOR_DELIVERY",

    COMPLETED:
        "COMPLETED",

    CANCELLED:
        "CANCELLED",

    REFUNDED:
        "REFUNDED",

};


/*
=========================================================
SELLER PAYMENT STATUS
=========================================================

Tracks what happens to money belonging to sellers.
=========================================================
*/

const SELLER_PAYMENT_STATUS = {

    NOT_RELEASED:
        "NOT_RELEASED",

    HELD:
        "HELD",

    RELEASED:
        "RELEASED",

    REFUNDED:
        "REFUNDED",

};


/*
=========================================================
PAYOUT STATUS
=========================================================
*/

const PAYOUT_STATUS = {

    NOT_RELEASED:
        "NOT_RELEASED",

    PENDING:
        "PENDING",

    PROCESSING:
        "PROCESSING",

    COMPLETED:
        "COMPLETED",

    FAILED:
        "FAILED",

};


/*
=========================================================
TRANSACTION TYPES
=========================================================

These describe financial events in the BIASHNET ledger.

PAYMENT
    Buyer successfully pays BIASHNET.

MARKETPLACE_SALE
    The financial sale generated by an order.

SELLER_HOLD
    Seller's net funds are moved into pending/held
    balance awaiting order completion.

COMMISSION_ACCRUAL
    BIASHNET records the commission earned from the sale
    while the funds are held.

COMMISSION_SETTLEMENT
    Commission becomes recognized/settled when seller
    funds are released.

SELLER_PAYOUT
    Seller's held funds become available.

WALLET_DEPOSIT
    Money deposited into an internal wallet.

WALLET_WITHDRAWAL
    Money withdrawn from an internal wallet.

WITHDRAWAL
    Generic withdrawal record.

REFUND
    Money returned to buyer.

=========================================================
*/

const TRANSACTION_TYPES = {

    /*
     * Buyer marketplace payment.
     */
    PAYMENT:
        "PAYMENT",


    /*
     * Marketplace sale.
     */
    MARKETPLACE_SALE:
        "MARKETPLACE_SALE",


    /*
     * Seller funds moved into pending balance.
     */
    SELLER_HOLD:
        "SELLER_HOLD",


    /*
     * BIASHNET commission recognized from the sale.
     */
    COMMISSION_ACCRUAL:
        "COMMISSION_ACCRUAL",


    /*
     * BIASHNET commission finalized at settlement.
     */
    COMMISSION_SETTLEMENT:
        "COMMISSION_SETTLEMENT",


    /*
     * Seller funds released from pending
     * into available balance.
     */
    SELLER_PAYOUT:
        "SELLER_PAYOUT",


    /*
     * Internal wallet funding.
     */
    WALLET_DEPOSIT:
        "WALLET_DEPOSIT",


    /*
     * Internal wallet withdrawal.
     */
    WALLET_WITHDRAWAL:
        "WALLET_WITHDRAWAL",


    /*
     * Generic withdrawal event.
     */
    WITHDRAWAL:
        "WITHDRAWAL",


    /*
     * Refund.
     */
    REFUND:
        "REFUND",

};


/*
=========================================================
ORDER COMPLETION CODE STATUS
=========================================================
*/

const ORDER_CODE_STATUS = {

    NOT_GENERATED:
        "NOT_GENERATED",

    ACTIVE:
        "ACTIVE",

    USED:
        "USED",

    EXPIRED:
        "EXPIRED",

    CANCELLED:
        "CANCELLED",

};


/*
=========================================================
SETTLEMENT STATUS
=========================================================

Stored on orders to describe seller fund lifecycle.
=========================================================
*/

const SETTLEMENT_STATUS = {

    NOT_STARTED:
        "NOT_STARTED",

    PENDING_COMPLETION:
        "PENDING_COMPLETION",

    PARTIALLY_SETTLED:
        "PARTIALLY_SETTLED",

    SETTLED:
        "SETTLED",

    FAILED:
        "FAILED",

};


/*
=========================================================
STOCK STATUS
=========================================================
*/

const STOCK_STATUS = {

    NOT_DEDUCTED:
        "NOT_DEDUCTED",

    DEDUCTED:
        "DEDUCTED",

    RESTORED:
        "RESTORED",

};


/*
=========================================================
LEDGER DIRECTIONS
=========================================================
*/

const TRANSACTION_DIRECTIONS = {

    CREDIT:
        "CREDIT",

    DEBIT:
        "DEBIT",

};


/*
=========================================================
MINIMUM WITHDRAWAL
=========================================================
*/

const MIN_WITHDRAWAL_AMOUNT = 10;


/*
=========================================================
EXPORTS
=========================================================
*/

module.exports = {

    PAYMENT_METHODS,

    PAYMENT_PROVIDERS,

    PAYMENT_STATUS,

    ORDER_STATUS,

    SELLER_PAYMENT_STATUS,

    PAYOUT_STATUS,

    TRANSACTION_TYPES,

    ORDER_CODE_STATUS,

    SETTLEMENT_STATUS,

    STOCK_STATUS,

    TRANSACTION_DIRECTIONS,

    MIN_WITHDRAWAL_AMOUNT,

};